//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int DonorID { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string Street { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public int BloodGroupID { get; set; }
        public System.DateTime DonationDate { get; set; }
    
        public virtual BloodGroup BloodGroup { get; set; }
    }
}
